version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: servicos
      MYSQL_USER: grupo3
      MYSQL_PASSWORD: baguette
    ports:
      - "5423:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  orders:
    build: ./Orders
    container_name: orders_service
    ports:
      - "5600:5600"
    volumes:
      - ./Orders:/app
      - ./Listas:/app/Listas
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: grupo3
      DB_PASSWORD: baguette
      DB_NAME: servicos

  notifications:
    build: ./Notifications
    container_name: notifications_service
    ports:
      - "5800:5800"
    volumes:
      - ./Notifications:/app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: grupo3
      DB_PASSWORD: baguette
      DB_NAME: servicos

volumes:
  db_data:
